[build]
  publish = "out"
  command = "npm run build && npm run export"
  ignore = "if [ $CACHED_COMMIT_REF == $COMMIT_REF ]; then (exit 1); else git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../..; fi;"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
